# Generated by Django 3.1.4 on 2021-01-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_auto_20210106_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('location', models.TextField(verbose_name='Место проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата проведения')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='StudentsInEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='например, участник или победитель', max_length=50, verbose_name='Роль студента в мероприятии')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventsForStudent', to='events.events', verbose_name='Мероприятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsInEvents', to='app.students', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студенты в мероприятиях',
                'verbose_name_plural': 'Студенты в мероприятиях',
            },
        ),
    ]
