# Generated by Django 3.1.4 on 2021-01-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_auto_20210106_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dateStart', models.DateField(verbose_name='Дата начала работы над проектом')),
                ('dateEnd', models.DateField(verbose_name='Дата окончания работ над проектом')),
                ('links', models.TextField(verbose_name='Список ссылок')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('participants', models.ManyToManyField(related_name='studentsForTeam', to='app.Students', verbose_name='Участники')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamsForProject', to='projects.projects', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
