# Generated by Django 3.1.4 on 2021-01-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='universityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universities', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='specializationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specializations', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='specializations',
            name='facultyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='groupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentsinevents',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='studentsinevents',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentsinteams',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='studentsinteams',
            name='teamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teams', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='projectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.projects', verbose_name='Проект'),
        ),
    ]
