# Generated by Django 3.1.4 on 2021-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210103_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculties',
            old_name='universityId',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='groups',
            old_name='specializationId',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='specializations',
            old_name='facultyId',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='groupId',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentsinevents',
            old_name='eventId',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='studentsinevents',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentsinteams',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studentsinteams',
            old_name='teamId',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teams',
            old_name='projectId',
            new_name='project',
        ),
    ]
