# Generated by Django 3.1.4 on 2021-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210104_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='location',
            field=models.CharField(max_length=150, verbose_name='Город'),
        ),
    ]
