# Generated by Django 3.1.4 on 2021-01-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210106_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinevents',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventsForStudent', to='app.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='studentsinevents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsInEvents', to='app.students', verbose_name='Студент'),
        ),
    ]
