# Generated by Django 3.1.4 on 2021-01-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210106_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultiesOfUniversity', to='app.universities', verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupsOfSpecialization', to='app.specializations', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='specializations',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializationsOfFaculty', to='app.faculties', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentsOfGroup', to='app.groups', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='participants',
            field=models.ManyToManyField(related_name='studentsForTeam', to='app.Students', verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamsForProject', to='app.projects', verbose_name='Проект'),
        ),
    ]
