# Generated by Django 3.1.4 on 2021-01-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_employee_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinevents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='studentsinevents',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='teams',
            name='project',
        ),
        migrations.AlterField(
            model_name='employee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.students', verbose_name='Студент'),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
        migrations.DeleteModel(
            name='StudentsInEvents',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
