# Generated by Django 3.1.4 on 2021-01-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210104_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='birtdate',
            new_name='birthdate',
        ),
    ]
