# Generated by Django 3.1.4 on 2021-01-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.students', verbose_name='Студент'),
        ),
    ]
