# Generated by Django 3.1.4 on 2021-01-07 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210106_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
    ]
